### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [yet-another-static-site-generator/yass#1]
The documentation mentions an AppImage, where can it be downloaded? Please also note https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake. Thank you very much for making an AppImage!

**Comment by thindil** [comment]
Hello and I'm sorry for confusion :)
This version of Readme.md is for not released yet version of the program,I just started preparing everything for it.
New version (with AppImage) will be probably available in few days. And file will be available in normal download location (I just want to replace old compressed binaries with AppImage).

**Comment by thindil** [comment]
Ok, so, this issue should be solved. Now AppImage is available for download and I hope I don't made too much mistakes while creating it :) Thank you for report and thank you very much for AppImage :)
If here will be any problems again, please feel free to reopen this issue or create new.
