### ISSUE TITLE
gcc: error: unrecognized command line option '-no-pie'

### ISSUE THREAD

**Issue by jquorning** [yet-another-static-site-generator/yass#5]
**Describe the bug**
Build fails on macOS Catalina.

**To Reproduce**
```sh
gprbuild
...
gcc: error: unrecognized command line option '-no-pie'
```

**Expected behavior**
Clean build

**Technical Info:**
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

**Comment by jquorning** [comment]
Suggestion: `dev` or `plain` or ´minimal´ Mode in `yass.gpr` that just builds without special compiler / linker flags.
`--no-pia` is really not crucial for a Yass to work.

**Comment by AJ-Ianozi** [comment]
Fixed with https://github.com/yet-another-static-site-generator/yass/pull/6 & https://github.com/yet-another-static-site-generator/yass/pull/7 thank you @jquorning !
